### ISSUE TITLE
爬取ssr账号成功后，开启ssr客户端显示解析错误。

### ISSUE THREAD

**Issue by zyp997** [maxmeng93/Get-Free-SS#10]
RT。@maxmeng93
<img src="https://s2.ax1x.com/2019/11/02/KqEveH.png" alt="KqEveH.png" border="0" />

**Comment by maxmeng93** [comment]
我这里是没有问题的。你检查下SSR软件的配置文件是不是有问题

**Comment by zyp997** [comment]
我重新生成了配置文件，也还是一样的问题。请问你用的是哪个ssr客户端？

**Comment by maxmeng93** [comment]
好像是这个 https://github.com/shadowsocksr-rm/shadowsocksr-csharp/releases
不过我一般只用SS

**Comment by zyp997** [comment]
有点奇怪，我用你发的链接的ssr客户端可以。
下面链接的就不行，一直提示解析错误。
https://github.com/shadowsocksrr/shadowsocksr-csharp/releases

**Comment by maxmeng93** [comment]
可能ssr链接解析规则有变化了，我研究下

**Comment by maxmeng93** [comment]
已经解决了，原因是传给配置文件中的端口号为字符串，旧版兼容而新版不兼容，只能是数字

**Comment by zyp997** [comment]
好的，谢谢。
