### ISSUE TITLE
读取软件配置文件失败，请检查 config/ss/url 是否设置正确

### ISSUE THREAD

**Issue by nonew** [maxmeng93/Get-Free-SS#12]
PS D:\Research\vpn\Get-Free-SS> npm start

> get-free-ss@3.0.1 start D:\Research\vpn\Get-Free-SS
> node ./main.js

D:\Research\vpn\Get-Free-SS\src\getSS.js:55
        throw 'SS：读取软件配置文件失败，请检查 config/ss/url 是否设置正确';
        ^
SS：读取软件配置文件失败，请检查 config/ss/url 是否设置正确
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get-free-ss@3.0.1 start: `node ./main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the get-free-ss@3.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abc\AppData\Roaming\npm-cache\_logs\2019-11-07T04_06_38_771Z-debug.log

**Comment by maxmeng93** [comment]
检查config文件夹下的软件路径

**Comment by nonew** [comment]
ss: {
    enable: true,
    url: 'C:\\Shadowsocks\\gui-config.json',
  },
  ssr: {
    enable: true,
    url: 'C:\\ShadowsocksR\\gui-config.json',
  },
我只有Shadowsocks，没有ShadowsocksR，ShadowsocksR是做什么用的，从哪里下载？

**Comment by maxmeng93** [comment]
那就把 ssr 下的 enable 改为 false

**Comment by zyp997** [comment]
仔细看说明，要双右斜杠转义。
shadowsocksR也是科学上网工具。可以在GitHub上搜索一下。@nonew

**Comment by nonew** [comment]
@zyp997 用的是双斜杠，贴上来就变成了单斜杠。

抓取成功后，shadowsocksR启动出错：
![image](https://user-images.githubusercontent.com/6738220/68386845-ed3b5700-0197-11ea-965c-428b84b211e4.png)
Shadowsocks试了好几个服务器都上不了google。

**Comment by maxmeng93** [comment]
看下package. json文件中的版本是不是3.0.2，不是就更新下代码

**Comment by zyp997** [comment]
作者说的是正解，要在release下载最新的压缩包。
爬取的账号容易失效，也没办法。@nonew
