### ISSUE TITLE
后续会支持更多的网站爬取账号吗？

### ISSUE THREAD

**Issue by zyp997** [maxmeng93/Get-Free-SS#3]
RT。
还有就是如果网站被墙，希望能够实现通过代理进入网站进行爬取。
@maxmeng93

**Comment by maxmeng93** [comment]
有可能会做吧，但是目前这个网站也能基本解决需求了，而且我现在不知道我这个仓库有没有法律分险，所以我会谨慎一点

**Comment by zyp997** [comment]
好的，谢谢。
还有就是反馈一个问题：已经成功替换了shadowsocks下的config文件，但是打开软件还是没有显示节点。

**Comment by maxmeng93** [comment]
双击图标，就会显示更新后的节点

**Comment by zyp997** [comment]
就是已经自动替换了config文件的节点，启动shadowsocks时还是没显示任何节点。是不是导入节点的格式错误，才导致了无法显示出节点。
<img src="https://s2.ax1x.com/2019/10/08/uWlIyD.png" alt="uWlIyD.png" border="0">
<img src="https://s2.ax1x.com/2019/10/08/uWl5QO.png" alt="uWl5QO.png" border="0">

**Comment by maxmeng93** [comment]
你可以自己先随便添加一个节点，然后再用命令替换一下，看看格式是否相同。

**Comment by maxmeng93** [comment]
看你的图片，这个配置文件有问题，软件是下载的README.md 中提到的那款吗？服务器地址，端口，密码，都是错误的。

**Comment by maxmeng93** [comment]
我现在手边没有电脑，明天回上海后，我会看看问题出在哪里。

**Comment by zyp997** [comment]
> 看你的图片，这个配置文件有问题，软件是下载的README.md 中提到的那款吗？服务器地址，端口，密码，都是错误的。

好像就是错的格式，我去看了下生成的data.json文件，也是差不多的格式。

**Comment by maxmeng93** [comment]
已经修复了，原因是爬取的网站DOM结构变更了，导致爬取信息错误

**Comment by zyp997** [comment]
ok，成功了。
还有就是有个建议：希望能添加一份未添加节点前的“gui-config.json”文件，提示把此文件移动到shadowsocks目录下。
因为一开始运行程序，不会自动生成此文件。直接用命令“npm start”进行替换，会报错。

**Comment by maxmeng93** [comment]
配置文件还是应该由软件生成。如果因为软件版本升级，导致配置文件内容发生变化，直接使用我提供的文件可能会发生错误。
我会在 README.md 文件里，写清楚应该先启动软件，生成配置文件后，再运行命令。

**Comment by zyp997** [comment]
好的，谢谢。
