### ISSUE TITLE
网站无法爬取，请检查 https://www.youneed.win/free-ss 是否可以正常打开。

### ISSUE THREAD

**Issue by zyp997** [maxmeng93/Get-Free-SS#4]
RT。@maxmeng93
已改hosts文件，多次尝试之后，一直显示如图错误。
<img src="https://s2.ax1x.com/2019/10/13/ujOjZd.png" alt="ujOjZd.png" border="0" />

**Comment by zyp997** [comment]
换了多个IP，能够正常打开网站。但依然一直显示如图错误。

**Comment by maxmeng93** [comment]
现在可以吗？我这边是没有问题的

**Comment by zyp997** [comment]
现在可以了，是网站限制的问题吗？

**Comment by maxmeng93** [comment]
应该不是，我有时候也打不开。有时候又会自动跳转到127.0.0.1上。目前还不知道原因是什么

**Comment by zyp997** [comment]
好吧，谢谢。
