### ISSUE TITLE
没填入ss/ssr的路径，就没有生成相应的json文件

### ISSUE THREAD

**Issue by zyp997** [maxmeng93/Get-Free-SS#5]
RT。
没填入ss/ssr的路径，爬取时会报错，并且data文件夹下没有生成相应的json文件。

**Comment by zyp997** [comment]
填入路径后，ss账号爬取成功，ssr账号爬取时出现错误：SSR：target2 error

**Comment by maxmeng93** [comment]
无法重现问题。
可以查看下面的GIF图，我试了把URL注释掉和不填URL时，都不会出错

![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/Get-Free-SS-issues-5-No1.jpvi4c1ti5g.gif)

**Comment by zyp997** [comment]
好的，谢谢。我以为填入不存在“gui-config.json”文件的路径，也会自动在data文件夹下生成相应的爬取的文件。
