### ISSUE TITLE
【运行报错】失败：请检查此页面能否正常打开 https://www.youneed.win/free-ss

### ISSUE THREAD

**Issue by w4ctech** [maxmeng93/Get-Free-SS#8]
``clone``源码后，我将index.js的``ss``和``ssr``路径修改问本地文件夹的``config``下，并将原有位于``
Shadowsocks``下的``gui-config.json``粘贴```config``文件夹下。
![image](https://user-images.githubusercontent.com/33955669/67365324-0642e600-f5a4-11e9-9879-5e8cae9b92e6.png)
运行过程报错如下
![image](https://user-images.githubusercontent.com/33955669/67365561-718cb800-f5a4-11e9-98d7-47ca0f8ab3e6.png)

``` bash
失败：请检查此页面能否正常打开 https://www.youneed.win/free-ss
SS：数据已保存在 /data/ss.json 文件中
SS：gui-config.json文件写入SS列表成功
失败：请检查此页面能否正常打开 https://www.youneed.win/free-ssr
SSR：数据已保存在 /data/ssr.json 文件中
SSR：gui-config.json文件写入SSR列表成功
```

**Comment by maxmeng93** [comment]
阅读文档，更新HOST

**Comment by maxmeng93** [comment]
有一个目标网站有反扒，今天我更新了文档，需要修改下HOST

**Comment by w4ctech** [comment]
已是最新代码

**Comment by w4ctech** [comment]
![image](https://user-images.githubusercontent.com/33955669/67370916-21b2ee80-f5ae-11e9-8274-1c184beaa15d.png)

**Comment by maxmeng93** [comment]
把旧的、不需要的HOST先注释掉，再试一试。104.31.74.55 那两行

**Comment by w4ctech** [comment]
已解决，thanks
